/**
 * /api/builds — create a pipeline build.
 *
 *   POST /api/builds
 *     Accepts { prompt, appName } to generate a spec from a user prompt,
 *     or falls back to the helpdesk fixture if no prompt is provided.
 *     Returns 201 with `{ buildId }`.
 */
import { NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';

import type { AppSpecTemplate } from '@heynxt/core-types';
import { db, builds } from '@heynxt/persistence';
import { validateSpecTemplate } from '@heynxt/agent-adapter';
import { helpdeskTicketingFixture } from '@heynxt/prompt-spec';

import { errorResponse } from '@/lib/api';

export const dynamic = 'force-dynamic';

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Sanitize LLM-generated spec: replace non-UUID IDs with real UUIDs.
 * LLMs often produce human-readable IDs like "bp-infra-pm-001" instead
 * of proper UUIDs — this fixes them before validation.
 */
function sanitizeSpec(spec: Record<string, unknown>): Record<string, unknown> {
  const s = structuredClone(spec);

  // Fix spec.appId
  const inner = s.spec as Record<string, unknown> | undefined;
  if (inner && typeof inner.appId === 'string' && !UUID_RE.test(inner.appId)) {
    inner.appId = randomUUID();
  }

  // Fix blueprintPlan.blueprintId
  const bp = s.blueprintPlan as Record<string, unknown> | undefined;
  if (bp && typeof bp.blueprintId === 'string' && !UUID_RE.test(bp.blueprintId)) {
    bp.blueprintId = randomUUID();
  }

  // Fix businessRules[].ruleId
  if (inner && Array.isArray(inner.businessRules)) {
    for (const rule of inner.businessRules as Array<Record<string, unknown>>) {
      if (typeof rule.ruleId === 'string' && !UUID_RE.test(rule.ruleId)) {
        rule.ruleId = randomUUID();
      }
    }
  }

  return s;
}

interface BuildRequest {
  prompt?: string;
  appName?: string;
  specJson?: string;
}

export async function POST(req: Request) {
  try {
    let body: BuildRequest = {};
    try {
      body = (await req.json()) as BuildRequest;
    } catch {
      // Empty body is OK — falls back to fixture
    }

    const prompt = body.prompt?.trim() || null;
    const appName = body.appName?.trim() || 'Helpdesk Ticketing System';

    // If a prompt was provided, generate the spec from it; otherwise use fixture
    let spec;
    let specJsonStr: string | null = null;

    if (prompt && body.specJson) {
      // Spec was pre-generated by the prompt flow
      try {
        spec = sanitizeSpec(JSON.parse(body.specJson));
      } catch {
        spec = helpdeskTicketingFixture;
      }
      specJsonStr = JSON.stringify(spec);
    } else if (prompt) {
      // Generate spec from prompt using LLM
      const generated = await generateSpecFromPrompt(prompt, appName);
      spec = sanitizeSpec(generated);
      specJsonStr = JSON.stringify(spec);
    } else {
      spec = helpdeskTicketingFixture;
      specJsonStr = JSON.stringify(helpdeskTicketingFixture);
    }

    const validation = validateSpecTemplate(spec as AppSpecTemplate);
    if (!validation.valid) {
      return NextResponse.json(
        { error: validation.errors },
        { status: 400 },
      );
    }

    const buildId = randomUUID();

    await db.insert(builds).values({
      id: buildId,
      appId: (spec as { spec?: { appId?: string } }).spec?.appId ?? randomUUID(),
      appName: (spec as { spec?: { appName?: string } }).spec?.appName ?? appName,
      prompt,
      specJson: specJsonStr,
      status: 'pending',
      createdAt: new Date(),
    });

    return NextResponse.json({ buildId }, { status: 201 });
  } catch (err) {
    return errorResponse(err);
  }
}

/**
 * Generate an AppSpecTemplate from a natural-language prompt via LLM.
 */
async function generateSpecFromPrompt(
  prompt: string,
  appName: string,
): Promise<Record<string, unknown>> {
  const apiKey = process.env['OPENROUTER_API_KEY'];
  if (!apiKey) throw new Error('OPENROUTER_API_KEY not set');

  const systemPrompt = `You are a senior software architect. Given an app description, produce a complete application specification as JSON.

The JSON must conform to this exact shape:
{
  "spec": {
    "appId": "<uuid>",
    "appName": "<string>",
    "entities": [
      {
        "name": "<string>",
        "fields": [
          { "name": "<string>", "type": "<FieldType>", "primaryKey": true/false, "nullable": true/false }
        ]
      }
    ],
    "businessRules": [
      { "ruleId": "<uuid>", "name": "<string>", "description": "<string>", "category": "<string>" }
    ],
    "uiRequirements": {
      "views": ["<string>"],
      "roles": ["<string>"]
    }
  },
  "blueprintPlan": {
    "blueprintId": "<uuid>",
    "blueprintName": "<string>",
    "domainModels": {},
    "constraints": [],
    "ruleImplementationHints": {}
  },
  "params": {}
}

FieldType is one of: uuid, string, text, integer, decimal, boolean, timestamp, enum, json.
IMPORTANT: All UUID fields (appId, blueprintId, ruleId) MUST be valid UUID v4 strings (e.g. "550e8400-e29b-41d4-a716-446655440000"). Do NOT use human-readable IDs like "bp-001".
Include 3-6 realistic entities with proper fields and relationships.
Return ONLY the JSON object. No markdown fences, no explanation.`;

  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://nosoftware.ai',
      'X-Title': 'NoSoftware.ai',
    },
    body: JSON.stringify({
      model: 'anthropic/claude-sonnet-4',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `App Name: ${appName}\nDescription: ${prompt}\n\nGenerate a complete AppSpecTemplate JSON.` },
      ],
      temperature: 0.2,
      max_tokens: 4096,
    }),
  });

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(`OpenRouter error ${res.status}: ${errBody}`);
  }

  const json = (await res.json()) as {
    choices: Array<{ message: { content: string } }>;
  };
  const raw = json.choices[0]?.message?.content ?? '';
  const cleaned = raw.replace(/^```[a-z]*\n?/gm, '').replace(/```$/gm, '').trim();

  return JSON.parse(cleaned) as Record<string, unknown>;
}
