/**
 * Event processor - normalizes and routes runtime events.
 */

import crypto from 'crypto';
import { eq, and } from 'drizzle-orm';
import { db, runtimeEvents, eventProcessingLog, type RuntimeEvent, InsertRuntimeEvent, kpiSnapshots, kpiDefinitions, kpiCalculationJobs } from '@heynxt/persistence';
import { withTransaction } from '../database/db';

export interface ProcessedEvent extends RuntimeEvent {
  processed: boolean;
  deduplicated: boolean;
  routedTo?: string[]; // Target systems/workflows
}

/**
 * Event processor for normalizing and routing incoming events.
 */
export class EventProcessor {
  /**
   * Buffer for tracking recent events (for deduplication).
   * In production, use Redis cache with TTL.
   */
  private static eventBuffer: Map<string, number> = new Map();
  private static readonly BUFFER_WINDOW_MS = 5000; // 5 second window

  /**
   * Process an incoming runtime event.
   */
  static async processEvent(eventData: InsertRuntimeEvent): Promise<ProcessedEvent> {
    const startTime = Date.now();

    return await withTransaction(async (client) => {
      // Check for duplicate based on eventId + eventType combination
      const dedupKey = `${eventData.eventId}:${eventData.eventType}`;
      const isDuplicate = EventProcessor.eventBuffer.has(dedupKey);

      if (!isDuplicate) {
        // Add to buffer
        EventProcessor.eventBuffer.set(dedupKey, Date.now());
        this.cleanOldEntries();
      }

      // Determine routing based on source and event type
      const routedTo = this.determineRouting(eventData.source as any, eventData.eventType);

      // Insert event into database (id will be generated by DB via UUID function)
      const [insertedEvent] = await db
        .insert(runtimeEvents)
        .values({ ...eventData, id: crypto.randomUUID() })
        .returning()
        .execute(client);

      if (!insertedEvent || !insertedEvent.id) {
        throw new Error('Failed to insert runtime event');
      }

      // Log processing with required fields matching schema
      const [logEntry] = await db
        .insert(eventProcessingLog)
        .values({
          id: crypto.randomUUID(),
          eventId: insertedEvent.id,
          stepName: 'ingestion',
          status: 'completed' as const,
          resultMessage: isDuplicate ? 'Deduplicated event' : 'Processed successfully',
          metadata: { routedTo, dedupKey },
          createdAt: new Date(),
        })
        .returning()
        .execute(client);

      console.log(
        `Processed event ${insertedEvent.id}: source=${eventData.source}, type=${eventData.eventType}, deduplicated=${isDuplicate}, routing=${routedTo.join(',')}`
      );

      return {
        ...insertedEvent,
        processed: true,
        deduplicated: isDuplicate,
        routedTo,
      };
    });
  }

  /**
   * Process a batch of events.
   */
  static async processEventBatch(events: InsertRuntimeEvent[]): Promise<ProcessedEvent[]> {
    const results: ProcessedEvent[] = [];

    for (const event of events) {
      try {
        const result = await this.processEvent(event);
        results.push(result);
      } catch (error) {
        console.error(`Failed to process event ${event.eventId || 'unknown'}:`, error);
      }
    }

    return results;
  }

  /**
   * Determine routing targets based on source and type.
   */
  private static determineRouting(source: string, eventType: string): string[] {
    const routes: string[] = [];

    // Route PLC signals to workflow engine for process control
    if (source === 'plc') {
      routes.push('workflow_engine');
    }

    // Route barcode scans to genealogy tracking
    if (source === 'barcode_scanner') {
      routes.push('genealogy_tracker');
    }

    // Route sensor data to rules engine for monitoring
    if (source === 'sensor') {
      routes.push('rules_engine');
    }

    return routes;
  }

  /**
   * Clean old entries from event buffer.
   */
  private static cleanOldEntries(): void {
    const cutoff = Date.now() - this.BUFFER_WINDOW_MS;

    for (const [key, timestamp] of this.eventBuffer.entries()) {
      if (timestamp < cutoff) {
        this.eventBuffer.delete(key);
      }
    }
  }

  /**
   * Get duplicate key for an event.
   */
  private static getDuplicateKey(event: InsertRuntimeEvent): string {
    return `${event.eventId}:${event.eventType}`;
  }

  /**
   * Check if an event is in the deduplication buffer.
   */
  static async isDuplicate(eventId: string, eventType: string): Promise<boolean> {
    const key = `${eventId}:${eventType}`;
    return this.eventBuffer.has(key);
  }

  /**
   * Get processing statistics for a time window.
   */
  static async getProcessingStats(sinceMs?: number): Promise<{
    totalProcessed: number;
    deduplicatedCount: number;
    avgProcessingTimeMs: number;
  }> {
    const stats = await db
      .select({
        totalProcessed: kpiSnapshots.id,
      })
      .from(kpiSnapshots)
      .execute();

    return {
      totalProcessed: stats.length || 0,
      deduplicatedCount: 0,
      avgProcessingTimeMs: 0,
    };
  }

  /**
   * Get recent processing log entries.
   */
  static async getRecentLogs(limit = 100): Promise<Array<{ id: string; eventId: string; stepName: string; status: string; resultMessage?: string | null; createdAt: Date }>> {
    const logs = await db
      .select({
        id: eventProcessingLog.id,
        eventId: eventProcessingLog.eventId,
        stepName: eventProcessingLog.stepName,
        status: eventProcessingLog.status,
        resultMessage: eventProcessingLog.resultMessage,
        createdAt: eventProcessingLog.createdAt,
      })
      .from(eventProcessingLog)
      .orderBy(eventProcessingLog.createdAt)
      .limit(limit);

    return logs;
  }

  /**
   * Search processing logs by eventId.
   */
  static async searchLogsByEventId(eventId: string): Promise<Array<{ id: string; stepName: string; status: string; resultMessage?: string | null; createdAt: Date }>> {
    const results = await db
      .select({
        id: eventProcessingLog.id,
        stepName: eventProcessingLog.stepName,
        status: eventProcessingLog.status,
        resultMessage: eventProcessingLog.resultMessage,
        createdAt: eventProcessingLog.createdAt,
      })
      .from(eventProcessingLog)
      .where(eq(eventProcessingLog.eventId, eventId))
      .orderBy(eventProcessingLog.createdAt);

    return results;
  }
}
